import React, { useState } from "react";
import Modal from "../components/Modal";
import Button from "../components/Button";
function ModalPage() {
  const [showModal,setShowModal] = useState(false);
  const handleClick= ()=>{
      setShowModal(true)
  }
  const handleClose = ()=>{
    setShowModal(false);
  }
  const modal = <Modal onClose={handleClose } actionBar={<Button onClick={handleClose} primary rounded>I Accept</Button>}>
    <p>Here is and IMPORTANT agrrement that you need to accept it befor the operation</p>
  </Modal>
  return (
    <div>
      <Button onClick={handleClick} primary rounded>Open Modal</Button>
      {showModal&&modal}
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed suscipit tempus condimentum. Sed nec euismod erat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Duis egestas ut dolor vel aliquam. Cras at euismod orci. Cras at augue vel ante bibendum consequat. Vivamus varius, nisi at euismod blandit, ante erat laoreet nunc, id hendrerit ipsum neque ac lorem. Vestibulum tincidunt, nibh vitae iaculis cursus, eros lorem malesuada elit, sed egestas erat nulla eu urna. Morbi dolor mi, aliquet sed purus sit amet, ornare luctus lacus. Aenean non sollicitudin arcu, a tincidunt erat. Curabitur posuere sodales faucibus. Etiam sollicitudin, ipsum nec feugiat pellentesque, turpis ligula feugiat ipsum, non rhoncus nisi tellus dignissim augue. Etiam non dolor lorem. Vestibulum ultricies lacus ac sapien sagittis ornare. Nam at feugiat lacus. Maecenas tristique tortor id sapien sagittis dignissim. </p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed suscipit tempus condimentum. Sed nec euismod erat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Duis egestas ut dolor vel aliquam. Cras at euismod orci. Cras at augue vel ante bibendum consequat. Vivamus varius, nisi at euismod blandit, ante erat laoreet nunc, id hendrerit ipsum neque ac lorem. Vestibulum tincidunt, nibh vitae iaculis cursus, eros lorem malesuada elit, sed egestas erat nulla eu urna. Morbi dolor mi, aliquet sed purus sit amet, ornare luctus lacus. Aenean non sollicitudin arcu, a tincidunt erat. Curabitur posuere sodales faucibus. Etiam sollicitudin, ipsum nec feugiat pellentesque, turpis ligula feugiat ipsum, non rhoncus nisi tellus dignissim augue. Etiam non dolor lorem. Vestibulum ultricies lacus ac sapien sagittis ornare. Nam at feugiat lacus. Maecenas tristique tortor id sapien sagittis dignissim. </p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed suscipit tempus condimentum. Sed nec euismod erat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Duis egestas ut dolor vel aliquam. Cras at euismod orci. Cras at augue vel ante bibendum consequat. Vivamus varius, nisi at euismod blandit, ante erat laoreet nunc, id hendrerit ipsum neque ac lorem. Vestibulum tincidunt, nibh vitae iaculis cursus, eros lorem malesuada elit, sed egestas erat nulla eu urna. Morbi dolor mi, aliquet sed purus sit amet, ornare luctus lacus. Aenean non sollicitudin arcu, a tincidunt erat. Curabitur posuere sodales faucibus. Etiam sollicitudin, ipsum nec feugiat pellentesque, turpis ligula feugiat ipsum, non rhoncus nisi tellus dignissim augue. Etiam non dolor lorem. Vestibulum ultricies lacus ac sapien sagittis ornare. Nam at feugiat lacus. Maecenas tristique tortor id sapien sagittis dignissim. </p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed suscipit tempus condimentum. Sed nec euismod erat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Duis egestas ut dolor vel aliquam. Cras at euismod orci. Cras at augue vel ante bibendum consequat. Vivamus varius, nisi at euismod blandit, ante erat laoreet nunc, id hendrerit ipsum neque ac lorem. Vestibulum tincidunt, nibh vitae iaculis cursus, eros lorem malesuada elit, sed egestas erat nulla eu urna. Morbi dolor mi, aliquet sed purus sit amet, ornare luctus lacus. Aenean non sollicitudin arcu, a tincidunt erat. Curabitur posuere sodales faucibus. Etiam sollicitudin, ipsum nec feugiat pellentesque, turpis ligula feugiat ipsum, non rhoncus nisi tellus dignissim augue. Etiam non dolor lorem. Vestibulum ultricies lacus ac sapien sagittis ornare. Nam at feugiat lacus. Maecenas tristique tortor id sapien sagittis dignissim. </p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed suscipit tempus condimentum. Sed nec euismod erat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Duis egestas ut dolor vel aliquam. Cras at euismod orci. Cras at augue vel ante bibendum consequat. Vivamus varius, nisi at euismod blandit, ante erat laoreet nunc, id hendrerit ipsum neque ac lorem. Vestibulum tincidunt, nibh vitae iaculis cursus, eros lorem malesuada elit, sed egestas erat nulla eu urna. Morbi dolor mi, aliquet sed purus sit amet, ornare luctus lacus. Aenean non sollicitudin arcu, a tincidunt erat. Curabitur posuere sodales faucibus. Etiam sollicitudin, ipsum nec feugiat pellentesque, turpis ligula feugiat ipsum, non rhoncus nisi tellus dignissim augue. Etiam non dolor lorem. Vestibulum ultricies lacus ac sapien sagittis ornare. Nam at feugiat lacus. Maecenas tristique tortor id sapien sagittis dignissim. </p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed suscipit tempus condimentum. Sed nec euismod erat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Duis egestas ut dolor vel aliquam. Cras at euismod orci. Cras at augue vel ante bibendum consequat. Vivamus varius, nisi at euismod blandit, ante erat laoreet nunc, id hendrerit ipsum neque ac lorem. Vestibulum tincidunt, nibh vitae iaculis cursus, eros lorem malesuada elit, sed egestas erat nulla eu urna. Morbi dolor mi, aliquet sed purus sit amet, ornare luctus lacus. Aenean non sollicitudin arcu, a tincidunt erat. Curabitur posuere sodales faucibus. Etiam sollicitudin, ipsum nec feugiat pellentesque, turpis ligula feugiat ipsum, non rhoncus nisi tellus dignissim augue. Etiam non dolor lorem. Vestibulum ultricies lacus ac sapien sagittis ornare. Nam at feugiat lacus. Maecenas tristique tortor id sapien sagittis dignissim. </p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed suscipit tempus condimentum. Sed nec euismod erat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Duis egestas ut dolor vel aliquam. Cras at euismod orci. Cras at augue vel ante bibendum consequat. Vivamus varius, nisi at euismod blandit, ante erat laoreet nunc, id hendrerit ipsum neque ac lorem. Vestibulum tincidunt, nibh vitae iaculis cursus, eros lorem malesuada elit, sed egestas erat nulla eu urna. Morbi dolor mi, aliquet sed purus sit amet, ornare luctus lacus. Aenean non sollicitudin arcu, a tincidunt erat. Curabitur posuere sodales faucibus. Etiam sollicitudin, ipsum nec feugiat pellentesque, turpis ligula feugiat ipsum, non rhoncus nisi tellus dignissim augue. Etiam non dolor lorem. Vestibulum ultricies lacus ac sapien sagittis ornare. Nam at feugiat lacus. Maecenas tristique tortor id sapien sagittis dignissim. </p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed suscipit tempus condimentum. Sed nec euismod erat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Duis egestas ut dolor vel aliquam. Cras at euismod orci. Cras at augue vel ante bibendum consequat. Vivamus varius, nisi at euismod blandit, ante erat laoreet nunc, id hendrerit ipsum neque ac lorem. Vestibulum tincidunt, nibh vitae iaculis cursus, eros lorem malesuada elit, sed egestas erat nulla eu urna. Morbi dolor mi, aliquet sed purus sit amet, ornare luctus lacus. Aenean non sollicitudin arcu, a tincidunt erat. Curabitur posuere sodales faucibus. Etiam sollicitudin, ipsum nec feugiat pellentesque, turpis ligula feugiat ipsum, non rhoncus nisi tellus dignissim augue. Etiam non dolor lorem. Vestibulum ultricies lacus ac sapien sagittis ornare. Nam at feugiat lacus. Maecenas tristique tortor id sapien sagittis dignissim. </p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed suscipit tempus condimentum. Sed nec euismod erat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Duis egestas ut dolor vel aliquam. Cras at euismod orci. Cras at augue vel ante bibendum consequat. Vivamus varius, nisi at euismod blandit, ante erat laoreet nunc, id hendrerit ipsum neque ac lorem. Vestibulum tincidunt, nibh vitae iaculis cursus, eros lorem malesuada elit, sed egestas erat nulla eu urna. Morbi dolor mi, aliquet sed purus sit amet, ornare luctus lacus. Aenean non sollicitudin arcu, a tincidunt erat. Curabitur posuere sodales faucibus. Etiam sollicitudin, ipsum nec feugiat pellentesque, turpis ligula feugiat ipsum, non rhoncus nisi tellus dignissim augue. Etiam non dolor lorem. Vestibulum ultricies lacus ac sapien sagittis ornare. Nam at feugiat lacus. Maecenas tristique tortor id sapien sagittis dignissim. </p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed suscipit tempus condimentum. Sed nec euismod erat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Duis egestas ut dolor vel aliquam. Cras at euismod orci. Cras at augue vel ante bibendum consequat. Vivamus varius, nisi at euismod blandit, ante erat laoreet nunc, id hendrerit ipsum neque ac lorem. Vestibulum tincidunt, nibh vitae iaculis cursus, eros lorem malesuada elit, sed egestas erat nulla eu urna. Morbi dolor mi, aliquet sed purus sit amet, ornare luctus lacus. Aenean non sollicitudin arcu, a tincidunt erat. Curabitur posuere sodales faucibus. Etiam sollicitudin, ipsum nec feugiat pellentesque, turpis ligula feugiat ipsum, non rhoncus nisi tellus dignissim augue. Etiam non dolor lorem. Vestibulum ultricies lacus ac sapien sagittis ornare. Nam at feugiat lacus. Maecenas tristique tortor id sapien sagittis dignissim. </p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed suscipit tempus condimentum. Sed nec euismod erat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Duis egestas ut dolor vel aliquam. Cras at euismod orci. Cras at augue vel ante bibendum consequat. Vivamus varius, nisi at euismod blandit, ante erat laoreet nunc, id hendrerit ipsum neque ac lorem. Vestibulum tincidunt, nibh vitae iaculis cursus, eros lorem malesuada elit, sed egestas erat nulla eu urna. Morbi dolor mi, aliquet sed purus sit amet, ornare luctus lacus. Aenean non sollicitudin arcu, a tincidunt erat. Curabitur posuere sodales faucibus. Etiam sollicitudin, ipsum nec feugiat pellentesque, turpis ligula feugiat ipsum, non rhoncus nisi tellus dignissim augue. Etiam non dolor lorem. Vestibulum ultricies lacus ac sapien sagittis ornare. Nam at feugiat lacus. Maecenas tristique tortor id sapien sagittis dignissim. </p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed suscipit tempus condimentum. Sed nec euismod erat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Duis egestas ut dolor vel aliquam. Cras at euismod orci. Cras at augue vel ante bibendum consequat. Vivamus varius, nisi at euismod blandit, ante erat laoreet nunc, id hendrerit ipsum neque ac lorem. Vestibulum tincidunt, nibh vitae iaculis cursus, eros lorem malesuada elit, sed egestas erat nulla eu urna. Morbi dolor mi, aliquet sed purus sit amet, ornare luctus lacus. Aenean non sollicitudin arcu, a tincidunt erat. Curabitur posuere sodales faucibus. Etiam sollicitudin, ipsum nec feugiat pellentesque, turpis ligula feugiat ipsum, non rhoncus nisi tellus dignissim augue. Etiam non dolor lorem. Vestibulum ultricies lacus ac sapien sagittis ornare. Nam at feugiat lacus. Maecenas tristique tortor id sapien sagittis dignissim. </p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed suscipit tempus condimentum. Sed nec euismod erat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Duis egestas ut dolor vel aliquam. Cras at euismod orci. Cras at augue vel ante bibendum consequat. Vivamus varius, nisi at euismod blandit, ante erat laoreet nunc, id hendrerit ipsum neque ac lorem. Vestibulum tincidunt, nibh vitae iaculis cursus, eros lorem malesuada elit, sed egestas erat nulla eu urna. Morbi dolor mi, aliquet sed purus sit amet, ornare luctus lacus. Aenean non sollicitudin arcu, a tincidunt erat. Curabitur posuere sodales faucibus. Etiam sollicitudin, ipsum nec feugiat pellentesque, turpis ligula feugiat ipsum, non rhoncus nisi tellus dignissim augue. Etiam non dolor lorem. Vestibulum ultricies lacus ac sapien sagittis ornare. Nam at feugiat lacus. Maecenas tristique tortor id sapien sagittis dignissim. </p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed suscipit tempus condimentum. Sed nec euismod erat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Duis egestas ut dolor vel aliquam. Cras at euismod orci. Cras at augue vel ante bibendum consequat. Vivamus varius, nisi at euismod blandit, ante erat laoreet nunc, id hendrerit ipsum neque ac lorem. Vestibulum tincidunt, nibh vitae iaculis cursus, eros lorem malesuada elit, sed egestas erat nulla eu urna. Morbi dolor mi, aliquet sed purus sit amet, ornare luctus lacus. Aenean non sollicitudin arcu, a tincidunt erat. Curabitur posuere sodales faucibus. Etiam sollicitudin, ipsum nec feugiat pellentesque, turpis ligula feugiat ipsum, non rhoncus nisi tellus dignissim augue. Etiam non dolor lorem. Vestibulum ultricies lacus ac sapien sagittis ornare. Nam at feugiat lacus. Maecenas tristique tortor id sapien sagittis dignissim. </p>
    </div>
  );
}

export default ModalPage;
